require('core-js/fn/object/assign');
require('core-js/fn/object/values');
require('core-js/fn/string/includes');
require('core-js/fn/array/includes');
require('core-js/fn/math/cbrt');
require('core-js/fn/number/is-integer');
require('core-js/fn/number/is-nan');
require('classlist-polyfill');
require('intersection-observer');
